### ISSUE TITLE
CLI upgrades

### ISSUE THREAD

**Issue by alexpdev** [alexpdev/ebookAtty#5]
The cli needs more control options, and better help messages.

**Comment by RickVincent** [comment]
I am new to Python. Really don't know how to run your code with CLI. Already install your package by "pip3 install ebookatty", instead of "... ebookatty-alexpdev".
Can you comment more detail on how to run by CLI?

**Comment by RickVincent** [comment]
from your instruction, "ebookatty path/to/ebook.epub".
Where to start ebookatty? could you kindly provide the exact command line for e.g. Windows?

**Comment by alexpdev** [comment]
This is an incomplete project and doesn't have a functioning executable script.  If you want to use it as a a cli  your best bet is to clone it and run python -m ebookatty /path/to/ebook 

I will start working on the console script to make it easier to run it shouldn't take long

**Comment by alexpdev** [comment]
> from your instruction, "ebookatty path/to/ebook.epub". Where to start ebookatty? could you kindly provide the exact command line for e.g. Windows?

This is an incomplete project and doesn't have a functioning executable script. If you want to use it as a a cli your best bet is to clone it and run 

```
python -m ebookatty /path/to/ebook
```

I will start working on the console script to make it easier to run it shouldn't take long

**Comment by alexpdev** [comment]
> from your instruction, "ebookatty path/to/ebook.epub". Where to start ebookatty? could you kindly provide the exact command line for e.g. Windows?



> I am new to Python. Really don't know how to run your code with CLI. Already install your package by "pip3 install ebookatty", instead of "... ebookatty-alexpdev". Can you comment more detail on how to run by CLI?

@RickVincent 

I just applied some upgrades to this package.  If you re-clone it or run `pip install --upgrade ebookatty`  you should get the the upgraded version.  Then you will be able to run `ebookatty /path/to/ebook` from anywhere

**Comment by RickVincent** [comment]
Thanks Alex! Thanks for your update!
Another issue is, for couple epub book, I always gets error: 
cover_id = t.xpath("//opf:metadata/opf:meta[@name='cover']",
IndexError: list index out of range

Can you help to check?
Attached the opf file as below (pls unzip it due to limitation of github uploading.)
[content.zip](https://github.com/alexpdev/ebookAtty/files/8784452/content.zip)

**Comment by RickVincent** [comment]
This is another book with the same IndexError
[content.zip](https://github.com/alexpdev/ebookAtty/files/8784548/content.zip)

tried to modify the cover-id clause, but no luck...

**Comment by alexpdev** [comment]
@RickVincent I am closing this issue and opened another with your specific request, please see comments in new issue for further updates
